export enum MUTATION_KEY {
  LOGIN = 'LOGIN',
  POUR_OUT = 'POUR_OUT',
  CREATE_QUEUE_REQUEST = 'CREATE_QUEUE_REQUEST',
  CREATE_GRADE_INFORMATION = 'CREATE_GRADE_INFORMATION',
  GET_GOODS_DETAIL = 'GET_GOODS_DETAIL',
  SET_WEIGHT = 'SET_WEIGHT',
  CREATE_SHIPMENT = 'CREATE_SHIPMENT'
}

export enum QUERY_KEY {
  GET_QUEUE_GROUP = 'GET_QUEUE_GROUP',
  GET_QUEUE_GROUP_DETAIL = 'GET_QUEUE_GROUP_DETAIL',
  GET_BARCODE_DETAIL = 'GET_BARCODE_DETAIL',
  GET_SALES_BARCODE = 'GET_SALES_BARCODE',
  GET_ALL_GRADE = 'GET_ALL_GRADE',
  GET_GRADING_INFO = 'GET_GRADING_INFO',
  GET_WEIGH_INFO = 'GET_WEIGH_INFO',
  GET_PARTNERS = 'GET_PARTNERS',
  GET_INVOICE_LIST = 'GET_INVOICE_LIST',
  GET_INVOICE_DETAIL = 'GET_INVOICE_DETAIL',
  GET_GROUPING_LIST = 'GET_GROUPING_LIST',
  GET_GROUPING_DETAIL = 'GET_GROUPING_DETAIL',
  GET_SHIPMENT_LIST = 'GET_SHIPMENT_LIST',
  GET_CLIENTS = 'GET_CLIENTS'
}
