version: "3.9"
services:
  app:
    container_name: sentadel-api
    restart: unless-stopped
    build: .
    ports:
    - "3001:3000"
    volumes:
      - ./:/app/
    networks:
      - development

networks:
  development:
    name: development
    driver: bridge
