version: "3.3"

services:
  app:
    container_name: sentadel-fe
    restart: unless-stopped
    build: .
    ports:
      - 3001:3000
    networks:
      - development

networks:
  development:
    name: development
    driver: bridge
